<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * El campo "price" se guarda en centavos (misma convención de la clase),
     * de modo que 189900 representa $1.899,00.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'book_id' => 1,
                'title' => 'El nombre del viento',
                'author' => 'Patrick Rothfuss',
                'publisher_id' => 3,
                'isbn' => '9788433968692',
                'price' => 189900,
                'synopsis' => 'La crónica de Kvothe, músico, fugitivo y héroe, contada por él mismo en el Hotel del Inmortal. Una de las fantasías más celebradas del siglo XXI.',
                'stock' => 8,
                'cover' => null,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 2,
                'title' => 'La sombra del viento',
                'author' => 'Carlos Ruiz Zafón',
                'publisher_id' => 1,
                'isbn' => '9788408073581',
                'price' => 149900,
                'synopsis' => 'Daniel encuentra en el Cementerio de los Libros Olvidados un libro que cambiará su vida. Barcelona, misterio y literatura en estado puro.',
                'stock' => 12,
                'cover' => null,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 3,
                'title' => 'Cien años de soledad',
                'author' => 'Gabriel García Márquez',
                'publisher_id' => 5,
                'isbn' => '9788420405568',
                'price' => 129900,
                'synopsis' => 'La historia de la familia Buendía a lo largo de siete generaciones en el pueblo de Macondo. Obra cumbre del realismo mágico.',
                'stock' => 20,
                'cover' => null,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 4,
                'title' => 'Rayuela',
                'author' => 'Julio Cortázar',
                'publisher_id' => 2,
                'isbn' => '9789500737845',
                'price' => 119900,
                'synopsis' => 'La novela que se puede leer de dos maneras: de principio a fin o saltando capítulos como indica el tablero de dirección.',
                'stock' => 6,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 5,
                'title' => 'El Aleph',
                'author' => 'Jorge Luis Borges',
                'publisher_id' => 2,
                'isbn' => '9789500737531',
                'price' => 99900,
                'synopsis' => 'Cuentos donde el infinito, los laberintos y los espejos se cruzan con lo cotidiano. Uno de los libros fundamentales de la literatura en castellano.',
                'stock' => 10,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 6,
                'title' => 'Ficciones',
                'author' => 'Jorge Luis Borges',
                'publisher_id' => 3,
                'isbn' => '9788433968494',
                'price' => 109900,
                'synopsis' => 'El jardín de senderos que se bifurcan, Tlön Uqbar Orbis Tertius y otros relatos que redefinearon el cuento moderno.',
                'stock' => 7,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 7,
                'title' => 'La tregua',
                'author' => 'Mario Benedetti',
                'publisher_id' => 2,
                'isbn' => '9789500739634',
                'price' => 89900,
                'synopsis' => 'La historia de amor entre dos oficinistas de Montevideo, contada con la ternura y la ironía característica de Benedetti.',
                'stock' => 9,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 8,
                'title' => 'Los siete locos',
                'author' => 'Roberto Arlt',
                'publisher_id' => 4,
                'isbn' => '9789875666634',
                'price' => 94900,
                'synopsis' => 'Rupert, el Astrónogo y la Sociedad de los Leprosos urden un plan para sacudir la Buenos Aires de los años treinta.',
                'stock' => 5,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 9,
                'title' => 'Plata quemada',
                'author' => 'Ricardo Piglia',
                'publisher_id' => 3,
                'isbn' => '9788433968234',
                'price' => 124900,
                'synopsis' => 'El asalto a un camión de caudales y la fuga de dos criminales por el río de la Plata. Crónica novelada del crimen perfecto.',
                'stock' => 4,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 10,
                'title' => 'La ciudad y los perros',
                'author' => 'Mario Vargas Llosa',
                'publisher_id' => 5,
                'isbn' => '9788466339513',
                'price' => 139900,
                'synopsis' => 'La vida en el Colegio Militar Leoncio Prado vista a través de la "Corporación", un grupo de alumnos que impone su propia ley.',
                'stock' => 11,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 11,
                'title' => 'El perfume',
                'author' => 'Patrick Süskind',
                'publisher_id' => 1,
                'isbn' => '9788417846138',
                'price' => 104900,
                'synopsis' => 'Grenouille, nacido en un mercado de pescados de París, posee un don extraordinario: un olfato capaz de distinguir cualquier aroma.',
                'stock' => 15,
                'cover' => null,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'book_id' => 12,
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'publisher_id' => 1,
                'isbn' => '9788417846139',
                'price' => 159900,
                'synopsis' => 'Paul Atreides y su familia llegan a Arrakis, el desierto más letal del universo, donde se libra la lucha por la especia más valiosa.',
                'stock' => 14,
                'cover' => null,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
